name: 'meu_projeto_dbt'
version: '1.0.0'
config-version: 2

profile: 'laboratorio_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
models:
  meu_projeto_dbt:
    staging:
      +schema: STAGING
    core:
      +schema: CORE
