version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    ports:
      - "3000:3000"
    environment:
      # Configurações de banco de dados do Metabase (PostgreSQL recomendado para produção)
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase_password
      MB_DB_HOST: metabase-db
      
      # Configurações gerais
      MB_JAVA_TIMEZONE: America/Sao_Paulo
      
      # Configurações opcionais de e-mail (descomente e configure se necessário)
      # MB_EMAIL_SMTP_HOST: smtp.gmail.com
      # MB_EMAIL_SMTP_PORT: 587
      # MB_EMAIL_SMTP_USERNAME: seu-email@gmail.com
      # MB_EMAIL_SMTP_PASSWORD: sua-senha-app
      # MB_EMAIL_FROM_ADDRESS: seu-email@gmail.com
      # MB_EMAIL_SMTP_SECURITY: tls
    volumes:
      - metabase-data:/metabase-data
    networks:
      - metabase-network
    depends_on:
      - metabase-db
    restart: unless-stopped
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  metabase-db:
    image: postgres:15-alpine
    container_name: metabase-db
    hostname: metabase-db
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase_password
    volumes:
      - metabase-db-data:/var/lib/postgresql/data
    networks:
      - metabase-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  metabase-data:
    driver: local
  metabase-db-data:
    driver: local

networks:
  metabase-network:
    driver: bridge
